version: "3.4"
services:
  rabbitmq:
    # image: rabbitmq:3-management
    # hostname: rabbitmq
    # volumes:
    #   - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
    #   - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    #   - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
    #   - ./rabbitmq/logs:/var/log/rabbitmq/log
    # ports:
    #   - 5672:5672
    #   - 15672:15672
    # image: "rabbitmq:3.8.9-management"
    build: ./rabbitmq
    hostname: "rabbit"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_NODENAME: "rabbitmq@rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - "./rabbitmq/data:/var/lib/rabbitmq/mnesia/"
    # networks:
    #   - rabbitmq_go_net

  qanh_server:
    build: ./qanh-server
    ports:
      - "5001:5001"
    volumes:
      - ./qanh-server:/usr/src/app:cached
      - ./qanh-server/logs:/var/log/app:delegated
      - /usr/src/app/node_modules
    command: npm start
    container_name: qanh-server
    # networks:
    #   - rabbitmq_go_net

# networks:
#   rabbitmq_go_net:
#     driver: bridge